# EDA for kp.csv

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data = pd.read_csv('../data-police/KP2020.csv', encoding = 'CP949')
print(data.shape)
print(data.columns)
data.head(10)

(77077, 10)
Index(['RECV_DEPT_NM', 'RECV_CPLT_DM', 'NPA_CL', 'EVT_STAT_CD', 'EVT_CL_CD',
       'RPTER_SEX', 'HPPN_PNU_ADDR', 'HPPN_X', 'HPPN_Y', 'SME_EVT_YN'],
      dtype='object')

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,20/12/01 01:43:07.000000000,19,10,305,1.0,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y
1,대전청,20/12/01 02:05:04.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
2,대전청,20/12/01 02:06:52.000000000,13,10,601,1.0,NaN,127.404663,36.341685,NaN
3,충남청,20/12/01 02:37:25.000000000,19,10,606,3.0,충청남도 보령시 천북면 하만리 628-10,126.524980,36.474390,N
4,충남청,20/12/01 08:17:50.000000000,19,10,401,2.0,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN
5,충남청,20/12/01 02:50:39.000000000,19,10,301,2.0,충청남도 아산시 둔포면 석곡리(행정:둔포면) 1707,127.057462,36.920405,Y
6,대전청,20/12/01 03:22:39.000000000,13,10,107,2.0,대전광역시 대덕구 중리동(행정:중리동) 381-25,127.422406,36.363326,Y
7,대전청,20/12/01 03:24:26.000000000,13,10,406,1.0,대전광역시 유성구 봉명동(행정:온천1동) 575,127.341551,36.353696,NaN
8,충남청,20/12/01 07:37:18.000000000,19,10,402,1.0,충청남도 천안시 서북구 성환읍 성월리(행정:성환읍) 150,127.136142,36.917900,NaN
9,대전청,20/12/01 07:08:44.000000000,13,10,401,1.0,대전광역시 중구 석교동(석교동) 85-14,127.447545,36.306724,NaN

In [29]:
npa = ['본청', '서울청', '부산청', '대구청', '인천청', '광주청', '대전청', '울산청',
'경기남부청', '경기북부청', '강원청', '충북청', '충남청', '전북청', '전남청',
'경북청', '경남청', '제주청', '세종청']

npa_code = [1, 8, 9, 10, 11, 12, 13, 14, 15, 16,
17, 18, 19, 20, 21, 22, 23, 24, 31]

npa_dict = pd.DataFrame(npa, index = npa_code, columns = ['npa']).to_dict()

In [34]:
data.NPA_CL.replace(npa_dict['npa']).value_counts().sort_values()

울산청          4
광주청          8
제주청          8
대구청         11
경남청         18
경북청         18
경기북부청       22
강원청         22
부산청         29
인천청         32
전남청         38
전북청         61
서울청        109
충북청        156
경기남부청      215
세종청       2753
대전청      34763
충남청      38810
Name: NPA_CL, dtype: int64

In [35]:
data.EVT_STAT_CD.value_counts().sort_values()
# 사건상태코드 - 8: 지령취소, 3: 초기지령, 7: 종결요청 5: 도착, 10: 종결요청
# 7과 10의 종결요청이 뭐가 다른 건지 모르겠음

8         1
3         2
7        36
5        72
10    76966
Name: EVT_STAT_CD, dtype: int64

In [36]:
data.EVT_CL_CD.value_counts().sort_values()

405        1
105        8
214       13
504       18
212       26
213       27
109       33
204       41
610       46
507       57
207       67
607       69
106       74
603       81
108      110
209      149
602      172
502      179
308      212
505      250
303      286
211      286
304      327
208      334
206      384
202      400
205      420
508      438
509      484
403      516
506      573
503      637
609      649
306      893
606      979
305      984
104     1117
107     1121
402     1294
604     1315
406     1325
210     1554
215     1660
201     1845
302     2098
301     2578
401     6207
307     6437
501    16336
601    21967
Name: EVT_CL_CD, dtype: int64

In [44]:
codebook = pd.read_excel('../data-police/codeBook_v3.xlsx', sheet_name = '코드집', engine = 'openpyxl')

In [63]:
codebook_df = codebook.loc[codebook['컬럼명'] == 'EVT_CL_CD'][['코드명', '코드값']]
evt_name = list(codebook_df['코드명'].unique())
evt_code = list(codebook_df['코드값'].unique())
evt_dict = {code:name for code, name in zip(evt_code, evt_name)}

In [65]:
data.EVT_CL_CD.replace(evt_dict).value_counts().sort_values()

인피도주              1
납치감금              8
마약               13
경비업체요청           18
스토킹              26
학교폭력             27
아동학대(기타)         33
협박               41
위험동물             46
FTX              57
주거침입             67
서비스요청            69
성폭력              74
구조요청             81
아동학대(가정내)       110
수배불심자           149
화재              172
변사자             179
기타경범            212
가출 등            250
청소년비행           286
데이트폭력           286
무전취식승차          327
풍속영업            334
재물손괴            384
사기              400
도박              420
자살              438
실종(실종아동 등)      484
교통위반            516
분실습득            573
비상벨             637
재해재난            649
보호조치            893
기타_타기관          979
주취자             984
절도             1117
가정폭력           1121
교통불편           1294
소음             1315
음주운전           1325
기타형사범          1554
보이스피싱          1660
폭력             1845
행패소란           2098
시비             2578
교통사고           6207
위험방지           6437
상담문의          16336
내용확인불가        21967
Name: EVT_CL_CD, dtype: int64

In [71]:
df = data.loc[(data['EVT_CL_CD'].isin((215, 401))) & (data['NPA_CL'].isin((13, 19, 31)))]
df.shape
# 7787건으로 확 줄어듦

(7787, 10)

In [72]:
data21 = pd.read_csv('../data-police/KP2021.csv', encoding = 'CP949')

In [73]:
data21.shape

(2594060, 10)

In [74]:
data21.columns

Index(['RECV_DEPT_NM', 'RECV_CPLT_DM', 'NPA_CL', 'EVT_STAT_CD', 'EVT_CL_CD',
       'RPTER_SEX', 'HPPN_PNU_ADDR', 'HPPN_X', 'HPPN_Y', 'SME_EVT_YN'],
      dtype='object')

In [76]:
df21 = data21.loc[(data21['EVT_CL_CD'].isin((215, 401))) & (data21['NPA_CL'].isin((13, 19, 31)))]
df21.shape
# 250만건 -> 196140건

(196140, 10)

In [80]:
# kp2020, kp2021 데이터프레임 결합
new_df = pd.concat([df, df21], axis = 0)
new_df.shape

(203927, 10)

In [133]:
# datetime 전처리
import datetime
new_df['DateTime'] = new_df['RECV_CPLT_DM'].str.replace('/', '-').str.rstrip('.00000000').str.ljust(17, '0')
new_df['DateTime'] = '20' + new_df['DateTime']
new_df['DateTime'] = pd.to_datetime(new_df['DateTime'])
new_df.DateTime

4         2020-12-01 08:17:50
9         2020-12-01 07:08:44
10        2020-12-01 07:09:20
31        2020-12-01 01:36:38
53        2020-12-01 01:39:03
                  ...
2593994   2023-01-15 20:01:39
2594002   2023-01-16 21:26:56
2594007   2023-01-17 15:50:47
2594019   2023-01-14 17:35:38
2594035   2023-01-15 01:13:20
Name: DateTime, Length: 203927, dtype: datetime64[ns]

In [137]:
new_df.drop(['RECV_DEPT_NM', 'RECV_CPLT_DM'], axis = 1, inplace = True)

In [138]:
new_df

,RECV_DEPT_NM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,DateTime
4,충남청,19,10,401,2.0,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN,2020-12-01 08:17:50
9,대전청,13,10,401,1.0,대전광역시 중구 석교동(석교동) 85-14,127.447545,36.306724,NaN,2020-12-01 07:08:44
10,대전청,13,10,401,2.0,대전광역시 중구 석교동(행정:석교동) 88-11,127.447175,36.306694,NaN,2020-12-01 07:09:20
31,충남청,19,10,401,1.0,충청남도 서산시 대산읍 대로리(행정:대산읍) 216-3,126.412290,36.967612,NaN,2020-12-01 01:36:38
53,대전청,13,10,401,1.0,대전광역시 동구 대동(행정:대동) 355-14,127.447390,36.324597,NaN,2020-12-01 01:39:03
...,...,...,...,...,...,...,...,...,...,...
2593994,대전청,13,10,401,1.0,대전 서구 괴정동 88-6,127.384284,36.334507,NaN,2023-01-15 20:01:39
2594002,충남청,19,10,401,1.0,충청남도 태안군 근흥면 두야리(근흥면 ) 246-2,126.262393,36.751467,NaN,2023-01-16 21:26:56
2594007,충남청,19,10,215,2.0,NaN,NaN,NaN,NaN,2023-01-17 15:50:47
2594019,대전청,13,10,401,1.0,대전광역시 대덕구 신탄진동 (행정:신탄진동 ) 129-7,127.433785,36.450725,NaN,2023-01-14 17:35:38
2594035,대전청,13,10,401,1.0,대전광역시 대덕구 평촌동 (행정:덕암동 ) 346,127.428287,36.425403,Y,2023-01-15 01:13:20

In [139]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 203927 entries, 4 to 2594035
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   RECV_DEPT_NM   203927 non-null  object
 1   NPA_CL         203927 non-null  int64
 2   EVT_STAT_CD    203927 non-null  int64
 3   EVT_CL_CD      203927 non-null  int64
 4   RPTER_SEX      203927 non-null  float64
 5   HPPN_PNU_ADDR  189751 non-null  object
 6   HPPN_X         196847 non-null  float64
 7   HPPN_Y         196847 non-null  float64
 8   SME_EVT_YN     41283 non-null   object
 9   DateTime       203927 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(3), object(3)
memory usage: 27.1+ MB

# npa 데이터

In [142]:
datanpa = pd.read_csv('../data-police/NPA2020.csv', encoding = 'cp949')
print(datanpa.shape)

df_npa = datanpa.loc[(datanpa['EVT_CL_CD'].isin((215, 401))) & (datanpa['NPA_CL'].isin((13, 19, 31)))]
print(df_npa.shape)
# 117만건 -> 10만건

(1178244, 10)

,RECV_CPLT_DT,RECV_CPLT_TM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,20200101,7,13,10,501,2,대전광역시 중구 목동(행정:목동) 360,127.409270,36.333010,Y
1,20200101,132,13,10,501,1,대전광역시 중구 대흥동(대흥동) 499-1,127.421295,36.325575,NaN
2,20200101,39,13,10,501,1,NaN,127.404663,36.341685,NaN
3,20200101,110,13,10,601,3,NaN,0.000000,0.000000,NaN
4,20200101,342,13,10,601,1,NaN,127.404663,36.341685,NaN

In [167]:
# datetime 전처리
df_npa['Date'] = pd.to_datetime(df_npa['RECV_CPLT_DT'], format = '%Y%m%d')
df_npa['Time'] = df_npa['RECV_CPLT_TM'].astype(str)
df_npa['Time'] = df_npa['Time'].str.zfill(6)
df_npa['DateTime'] = df_npa['Date'].astype(str)
df_npa['DateTime'] = df_npa['DateTime'] + ' ' + df_npa.Time
df_npa['DateTime'] = pd.to_datetime(df_npa['DateTime'])

In [176]:
df_npa.drop(['RECV_CPLT_DT', 'RECV_CPLT_TM', 'Date', 'Time'], axis = 1, inplace = True)

# npa, kp 결합

In [177]:
df_npa

,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,DateTime
54,13,10,401,1,대전광역시 유성구 봉명동(행정:온천1동) 541-26,127.348625,36.353829,NaN,2020-01-01 00:21:35
66,13,10,401,1,대전광역시 중구 오류동(행정:오류동) 187-27,127.405055,36.328573,NaN,2020-01-01 00:43:01
117,13,10,401,3,대전광역시 동구 가양동 630,127.445780,36.345500,N,2020-01-01 18:43:35
144,13,10,401,1,대전광역시 동구 판암동(행정:판암2동) 237,127.459160,36.323490,NaN,2020-01-01 19:08:53
147,13,10,401,1,대전광역시 중구 태평동(태평2동) 378-7,127.394136,36.326646,NaN,2020-01-01 19:15:25
...,...,...,...,...,...,...,...,...,...
1177991,13,10,401,1,대전광역시 유성구 도룡동(행정:신성동) 3-1,127.384612,36.377690,Y,2020-11-20 12:57:06
1178035,13,5,401,1,대전광역시 유성구 봉명동(행정:온천1동) 651-1,127.347209,36.357588,,2020-11-22 00:03:22
1178051,13,5,401,1,대전광역시 유성구 장대동(행정:온천2동) 375-3,127.339844,36.358391,,2020-11-22 00:54:10
1178086,13,5,401,1,대전광역시 동구 신흥동(행정:신인동) 212,127.446090,36.320140,Y,2020-11-22 00:40:08
1178173,13,5,401,1,대전광역시 동구 신흥동(행정:신인동) 212,127.446090,36.320140,Y,2020-11-22 00:37:53

In [175]:
new_df

,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,DateTime
4,19,10,401,2.0,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN,2020-12-01 08:17:50
9,13,10,401,1.0,대전광역시 중구 석교동(석교동) 85-14,127.447545,36.306724,NaN,2020-12-01 07:08:44
10,13,10,401,2.0,대전광역시 중구 석교동(행정:석교동) 88-11,127.447175,36.306694,NaN,2020-12-01 07:09:20
31,19,10,401,1.0,충청남도 서산시 대산읍 대로리(행정:대산읍) 216-3,126.412290,36.967612,NaN,2020-12-01 01:36:38
53,13,10,401,1.0,대전광역시 동구 대동(행정:대동) 355-14,127.447390,36.324597,NaN,2020-12-01 01:39:03
...,...,...,...,...,...,...,...,...,...
2593994,13,10,401,1.0,대전 서구 괴정동 88-6,127.384284,36.334507,NaN,2023-01-15 20:01:39
2594002,19,10,401,1.0,충청남도 태안군 근흥면 두야리(근흥면 ) 246-2,126.262393,36.751467,NaN,2023-01-16 21:26:56
2594007,19,10,215,2.0,NaN,NaN,NaN,NaN,2023-01-17 15:50:47
2594019,13,10,401,1.0,대전광역시 대덕구 신탄진동 (행정:신탄진동 ) 129-7,127.433785,36.450725,NaN,2023-01-14 17:35:38
2594035,13,10,401,1.0,대전광역시 대덕구 평촌동 (행정:덕암동 ) 346,127.428287,36.425403,Y,2023-01-15 01:13:20

In [178]:
list(new_df.columns)

['NPA_CL',
 'EVT_STAT_CD',
 'EVT_CL_CD',
 'RPTER_SEX',
 'HPPN_PNU_ADDR',
 'HPPN_X',
 'HPPN_Y',
 'SME_EVT_YN',
 'DateTime']

In [179]:
# 발생지점 칼럼명 단일화
new_df.columns = ['NPA_CL', 'EVT_STAT_CD', 'EVT_CL_CD', 'RPTER_SEX', 'HPPN_OLD_ADDR', 'HPPN_X', 'HPPN_Y', 'SME_EVT_YN', 'DateTime']
new_df

,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,DateTime
4,19,10,401,2.0,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN,2020-12-01 08:17:50
9,13,10,401,1.0,대전광역시 중구 석교동(석교동) 85-14,127.447545,36.306724,NaN,2020-12-01 07:08:44
10,13,10,401,2.0,대전광역시 중구 석교동(행정:석교동) 88-11,127.447175,36.306694,NaN,2020-12-01 07:09:20
31,19,10,401,1.0,충청남도 서산시 대산읍 대로리(행정:대산읍) 216-3,126.412290,36.967612,NaN,2020-12-01 01:36:38
53,13,10,401,1.0,대전광역시 동구 대동(행정:대동) 355-14,127.447390,36.324597,NaN,2020-12-01 01:39:03
...,...,...,...,...,...,...,...,...,...
2593994,13,10,401,1.0,대전 서구 괴정동 88-6,127.384284,36.334507,NaN,2023-01-15 20:01:39
2594002,19,10,401,1.0,충청남도 태안군 근흥면 두야리(근흥면 ) 246-2,126.262393,36.751467,NaN,2023-01-16 21:26:56
2594007,19,10,215,2.0,NaN,NaN,NaN,NaN,2023-01-17 15:50:47
2594019,13,10,401,1.0,대전광역시 대덕구 신탄진동 (행정:신탄진동 ) 129-7,127.433785,36.450725,NaN,2023-01-14 17:35:38
2594035,13,10,401,1.0,대전광역시 대덕구 평촌동 (행정:덕암동 ) 346,127.428287,36.425403,Y,2023-01-15 01:13:20

In [208]:
whole_df = pd.concat([df_npa, new_df], axis = 0)
whole_df.shape

(308365, 9)

In [211]:
to_find_sametime = whole_df.DateTime.value_counts().reset_index()
sametime_list = list(to_find_sametime.loc[to_find_sametime['DateTime'] != 1]['index'].astype(str))
sametime_df = whole_df.loc[whole_df.DateTime.isin(sametime_list)]

In [214]:
sametime_df.sort_values(by = 'DateTime')

,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,DateTime
542,13,10,401,1,세종특별자치시 세종시 대평동(행정:대평동) 269-13,127.273928,36.469322,NaN,2020-01-01 05:45:06
1224,19,10,401,1,세종특별자치시 세종시 대평동(행정:대평동) 269-13,127.273928,36.469322,NaN,2020-01-01 05:45:06
770,13,10,401,2,충청남도 공주시 반포면 학봉리(반포면) 917(나동1층),127.251831,36.365180,NaN,2020-01-01 16:32:31
2505,19,10,401,2,충청남도 공주시 반포면 학봉리(반포면) 917(나동1층),127.251831,36.365180,NaN,2020-01-01 16:32:31
296,13,10,401,1,충청남도 금산군 금산읍 상리(행정:금산읍),127.481785,36.112216,NaN,2020-01-01 17:36:37
...,...,...,...,...,...,...,...,...,...
2584848,19,10,401,3,대전광역시 서구 우명동 (기성동 ) 417,127.279975,36.250661,NaN,2023-01-18 11:31:20
2583004,19,10,401,1,충청남도 아산시 송악면 역촌리(송악면 ) 502-4,127.006438,36.713149,NaN,2023-01-18 18:27:27
2585715,13,10,401,2,대전광역시 서구 월평동 (월평1동 ) 873,127.363939,36.354220,NaN,2023-01-18 18:27:27
2582959,31,10,215,2,세종특별자치시 세종시 연서면 봉암리(연서면 ) 54-89,127.284535,36.565027,Y,2023-01-18 18:38:01
2583199,13,10,401,1,대전광역시 대덕구 오정동 (행정:오정동 ),127.403651,36.357049,NaN,2023-01-18 18:38:01

In [216]:
exact_df = whole_df.drop_duplicates(['DateTime', 'HPPN_X', 'HPPN_Y'])
exact_df

,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,DateTime
54,13,10,401,1,대전광역시 유성구 봉명동(행정:온천1동) 541-26,127.348625,36.353829,NaN,2020-01-01 00:21:35
66,13,10,401,1,대전광역시 중구 오류동(행정:오류동) 187-27,127.405055,36.328573,NaN,2020-01-01 00:43:01
117,13,10,401,3,대전광역시 동구 가양동 630,127.445780,36.345500,N,2020-01-01 18:43:35
144,13,10,401,1,대전광역시 동구 판암동(행정:판암2동) 237,127.459160,36.323490,NaN,2020-01-01 19:08:53
147,13,10,401,1,대전광역시 중구 태평동(태평2동) 378-7,127.394136,36.326646,NaN,2020-01-01 19:15:25
...,...,...,...,...,...,...,...,...,...
2593994,13,10,401,1,대전 서구 괴정동 88-6,127.384284,36.334507,NaN,2023-01-15 20:01:39
2594002,19,10,401,1,충청남도 태안군 근흥면 두야리(근흥면 ) 246-2,126.262393,36.751467,NaN,2023-01-16 21:26:56
2594007,19,10,215,2,NaN,NaN,NaN,NaN,2023-01-17 15:50:47
2594019,13,10,401,1,대전광역시 대덕구 신탄진동 (행정:신탄진동 ) 129-7,127.433785,36.450725,NaN,2023-01-14 17:35:38
2594035,13,10,401,1,대전광역시 대덕구 평촌동 (행정:덕암동 ) 346,127.428287,36.425403,Y,2023-01-15 01:13:20

In [218]:
accident_df = exact_df.loc[exact_df['EVT_CL_CD'] == 401]
voice_df = exact_df.loc[exact_df['EVT_CL_CD'] == 215]
print(accident_df.shape)
print(voice_df.shape)

(260956, 9)
(45537, 9)

In [220]:
accident_df.to_csv('../data-police/car_accident.csv', encoding = 'CP949', index = False)
voice_df.to_csv('../data-police/voice_phishing.csv', encoding = 'CP949', index = False)